# Generated by Django 4.2 on 2024-12-14 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('is_deleted', models.BooleanField(blank=True, default=False, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='')),
                ('thumbnail_file', models.ImageField(blank=True, null=True, upload_to='')),
                ('file_tags', models.CharField(blank=True, max_length=128, null=True)),
                ('file_url', models.CharField(blank=True, max_length=128, null=True)),
                ('file_name', models.CharField(blank=True, max_length=128, null=True)),
                ('bucket_name', models.CharField(default='chat-bucket', max_length=128)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
